# For every try-except, there should be at least one test that generates a failure.
# Do I need to add more sophistication to my sys.exit() call to support testing without crashing?
